services:
  ram-ms-item:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ram-ms-item
    restart: unless-stopped
    ports:
      - '3006:3006'
    env_file:
      - .env
    depends_on:
      item-db:
        condition: service_healthy
    networks:
      - ram-shared-network

  item-db:
    image: mariadb:latest
    container_name: ram-ms-item-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_PASSWORD:-ram_password}
      MARIADB_DATABASE: ${DATABASE_NAME:-ram-ms-item-db}
      MARIADB_USER: ${DATABASE_USER:-root}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD:-ram_password}
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql

    networks:
      - ram-shared-network
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  ram-shared-network:
    external: true

volumes:
  mariadb_data:
